version: '3.8'

services:
  node-app:
    image: node:20-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/doengnce7/Documents/devcontainrs-test:/workspace
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - NODE_ENV=development
    extra_hosts:
      - "postgres:host-gateway"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_started
    command: sh -c "apk add docker-cli && rm -rf /root/.npm /workspace/node_modules /workspace/package-lock.json && cd /workspace && npm install && npm run dev"
    user: root
    working_dir: /workspace

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: